version: '3.4'

services:
  powertcp.vert:
    image: ${DOCKER_REGISTRY-}powertcpvert
    build:
      context: .
      dockerfile: PoweTCP.Vert/Dockerfile
    networks:
      dev_network:
        ipv4_address: 172.18.0.3
  ftpserver:
    image: stilliard/pure-ftpd
    container_name: ftpd_server
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - ./ftp_server/data:/home/ftpusers/test/
      - ./ftp_server/passwd:/etc/pure-ftpd/passwd
    environment:
      TZ: Asia/Tokyo
      FTP_USER_NAME: admin
      FTP_USER_PASS: p@ss
      FTP_USER_HOME: /home/ftpusers/test
    restart: always
    networks:
      dev_network:
        ipv4_address: 172.18.0.4
networks: 
    dev_network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.18.0.0/24